import data from "@/lib/registry-data.json";

/**
 * The catalogue as data, generated by scripts/sync-registry.mjs from the real
 * source files. A static import rather than an fs read: the docs page shows
 * exactly the file `shadcn add` copies, and the bundler doesn't have to trace
 * the whole project to work that out.
 */

export type RegistryFile = {
  path: string;
  type: string;
  target: string | null;
  displayPath: string;
  content: string;
};

export type RegistryItem = {
  name: string;
  type: string;
  title: string;
  description: string;
  author: string | null;
  dependencies: string[];
  registryDependencies: string[];
  categories: string[];
  files: RegistryFile[];
};

export const registryItems = data as RegistryItem[];

export function loadRegistryItem(name: string): RegistryItem | undefined {
  return registryItems.find((item) => item.name === name);
}

export type PropsBlock = { name: string; body: string };

/**
 * Pulls every `export interface *Props { … }` straight out of the source.
 * Zero dependencies, cannot drift from the file it documents, and the JSDoc
 * on each prop comes along for free.
 */
export function extractPropsInterfaces(source: string): PropsBlock[] {
  const out: PropsBlock[] = [];
  const re = /export interface (\w*Props)\b[^{]*\{/g;
  let match: RegExpExecArray | null;

  while ((match = re.exec(source))) {
    const start = match.index + match[0].length;
    let depth = 1;
    let i = start;
    while (i < source.length && depth > 0) {
      const c = source[i];
      if (c === "{") depth++;
      else if (c === "}") depth--;
      i++;
    }
    out.push({ name: match[1], body: source.slice(start, i - 1).trim() });
  }

  return out;
}
