import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Vendored shadcn primitives. We didn't write them and a future
    // `shadcn add` overwrites them, so linting them only produces noise we
    // cannot fix. Our own code lives in src/registry and src/app.
    "src/components/ui/**",

    // Generated by scripts/sync-registry.mjs — mirrors of src/registry/**,
    // which is what actually gets linted.
    "src/components/ecomcn/**",
    "src/hooks/use-*.ts",
    "src/lib/filter-params.ts",
  ]),

  {
    // Rule 07 of the house style, enforced rather than documented: a block
    // has to compile in a Vite or React Router project too. Take an image or
    // a link as a prop; never reach for the framework.
    files: ["src/registry/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["next", "next/*", "next/**"],
              message:
                "Registry blocks must compile in any React project. Accept an image or link element as a prop instead of importing from next/*.",
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
